#!/bin/bash

echo "[*] Installing Python dependencies system-wide with override..."

export PYTHONWARNINGS="ignore"
python3 -m pip install --break-system-packages --no-input --quiet \
    typer[all] pydantic python-gnupg InquirerPy

echo "[+] Python dependencies installed."

# Ensure launcher is executable
chmod +x /usr/bin/cr3di
